export const ACTION_TYPES = {
  LOGIN: Symbol("LOGIN"),
  LOGIN_DEFAULT: Symbol("LOGIN_DEFAULT"),
  LOGIN_CALLING: Symbol("LOGIN_CALLING"),
  LOGIN_ERROR: Symbol("LOGIN_ERROR"),
  LOGIN_SUCCESS: Symbol("LOGIN_SUCCESS"),
  LOGIN_TIMEOUT: Symbol("LOGIN_TIMEOUT"),
  SET_DATA: Symbol("SET_DATA"),
  RESET_DATA: Symbol("RESET_DATA"),
};
