export const ACTION_TYPES = {
  SET_IS_COMPLETE_ANSWER: Symbol("SET_IS_COMPLETE_ANSWER"),
  SET_IS_ANSWERED: Symbol("SET_IS_ANSWERED"),
  SET_IS_ANSWERED_CORRECT: Symbol("SET_IS_ANSWERED_CORRECT"),
  GET_QUIZ_BY_LEARNING_OBJECT_ID: Symbol("GET_QUIZ_BY_LEARNING_OBJECT_ID"),
  SET_QUIZ_TYPE: Symbol("SET_QUIZ_TYPE"),
  SET_QUIZ: Symbol("SET_QUIZ"),
  SET_GET_QUIZ_STATE: Symbol("SET_GET_QUIZ_STATE"),
  UPDATE_QUIZ_STATUS: Symbol("UPDATE_QUIZ_STATUS"),
  SET_UPDATE_QUIZ_STATUS_STATE: Symbol("SET_UPDATE_QUIZ_STATUS_STATE"),
};
